services:
  postgres_db:
    image: postgres:17.5-alpine
    restart: always
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ../infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ../.env

  redis:
    image: redis:8.4.0-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:v1.16.2
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  api-fastapi:
    build:
      context: ..
      dockerfile: infra/Dockerfile.fastapi
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../services/api-fastapi:/app
      - ../pipelines:/app/pipelines
      - ../prompts:/app/prompts
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
      - QDRANT_HOST=qdrant
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION}
      - EMBEDDING_DISTANCE=${EMBEDDING_DISTANCE}
      - COHERE_API_KEY=${COHERE_API_KEY}
    depends_on:
      - postgres_db
      - qdrant
    env_file:
      - ../.env
    command: sh -c "alembic upgrade head && python scripts/seed_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  api-flask:
    build:
      context: ..
      dockerfile: infra/Dockerfile.flask
    container_name: flask_admin
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ../services/api-flask:/app
      - ../pipelines:/app/pipelines
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
      - REDIS_URL=${REDIS_URL}
      - QDRANT_HOST=qdrant
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION}
      - EMBEDDING_DISTANCE=${EMBEDDING_DISTANCE}
      - COHERE_API_KEY=${COHERE_API_KEY}
    depends_on:
      - qdrant
      - redis
      - postgres_db
    env_file:
      - ../.env
    command: gunicorn --bind 0.0.0.0:5000 --timeout 300 --workers 1 --reload run:app

  react-app:
    build:
      context: ..
      dockerfile: infra/Dockerfile.react
    container_name: react_app
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ../ui/react-app:/app
      - /app/node_modules
    depends_on:
      - api-fastapi
    environment:
      - VITE_API_URL=${VITE_API_URL}
    env_file:
      - ../.env
      
volumes:
  postgres_data:
  qdrant_data:
  redis_data: